### ISSUE TITLE
crash on world load with Hwyla-1.8.10-B23_1.11

### ISSUE THREAD

**Issue by SDUBZ** [TehNut-Mods/HWYLA#52] opened 2017-02-11 17:42 UTC
#### Issue Description:
Hwyla for 1.11.2 crashes me after joining world and it didnt do this before first occurance

#### What happens:
it crashes upon world load

#### What you expected to happen:
to join my world without a crash

#### Steps to reproduce:

1. load into world with Hwyla-1.8.10-B23_1.11
2. get crash
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Hwyla: Hwyla-1.8.10-B23_1.11
- Minecraft: 1.11.2
- Forge: 1.11.2-2227

#### Possible Conflicting Mods (Provide their version, as well)
mods i was using at the time 
[print.txt](https://github.com/TehNut/HWYLA/files/768762/print.txt)

crash report: 
[crash-2017-02-12_04.33.56-client.txt](https://github.com/TehNut/HWYLA/files/768763/crash-2017-02-12_04.33.56-client.txt)

**Comment by TehNut** [comment] 2017-02-11 18:07
Dupe of #43 which was not reproducable.

**Comment by SDUBZ** [comment] 2017-02-11 18:22
but what is waila split?

**Comment by TehNut** [comment] 2017-02-11 18:23
It is a field that defines a string for Waila to split on.

**Comment by SDUBZ** [comment] 2017-02-11 18:34
yeah because it said it couldnt be found the class for it in the log i will retry getting to trigger again so i can show you the log

**Comment by SDUBZ** [comment] 2017-02-11 21:27
on further testing its mod inter action causing this crash, after removing convenient additions,integrated dynamic and tunnels this crash does not occur now

**Closed as completed** 2017-02-14 03:51 UTC
Labels: invalid, other mod
